// <auto-generated />
namespace Car_Rent_All.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SzerzodesekModositas2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SzerzodesekModositas2));
        
        string IMigrationMetadata.Id
        {
            get { return "202203301954553_SzerzodesekModositas2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
